// This file was automatically generated by users/ZenghaoWang/ComboGen.py.
#include "quantum.h"
#include "process_combo.h"
#include "config.h"
#include "keycodes.h"
#include "tap_dance.h"
#include "combos.h"

enum combo_events {
	WF_SCLN,
	CK_EQUAL,
	COMMA_DOT_BSLSH,
	UY_DASH,
	HCOMMA_BANG,
	S_COMMA_LEFT_ARROW,
	S_DOT_RIGHT_ARROW,
	AO_CAPSLOCK,
	RS_CAPSWORD,
	NE_ESC,
	QQUOT_RESET,
	ZSLASH_POWER_OPTS,
	BSPCEV_EVERY,
	BSPCU_YOU,
	BSPCU_AND,
	BSPCN_NOT,
	BSPCF_FOR,
	BSPCH_HERE,
	BSPCT_THE,
	BSPCM_MENT,
	BSPCG_ING,
	BSPCO_OUGH,
	BSPCI_ION,
	BSPCIS_IONS,
	BSPCTA_THAT,
	BSPCQ_QUE,
	BSPCK_KEY,
	BSPCTS_THIS,
	BSPCTH_THAT,
	BSPCDN_DONT,
	BSPCL_LOOK,
	BSPCE_EYE,
	BSPCW_WHAT,
	BSPCP_PARA,
	BSPCAT_AND_THE,
	BSPC_Z_ZENGHAO,
	BSPCAT_IN_THE,
	BSPCOT,
	BSPC_B_BASSOON,
	JU_JUST,
	HV_HAVE,
	QK_QMK,
	KB_KEYBOARD,
	WA_WAS,
	FR_FROM,
	FA_FACE,
	OD_OULD,
	WI_WITH,
	IE_IKE,
	AK_AWKWARD,
	RM_REMEMBER,
	SY_SYMPHON,
	WR_WARD,
	COMBO_LENGTH
};
uint16_t COMBO_LEN = COMBO_LENGTH;

const uint16_t PROGMEM W_F_COMBO[] = {KC_W, LT_F_WINDOW, COMBO_END};
const uint16_t PROGMEM C_K_COMBO[] = {KC_X, KC_C, COMBO_END};
const uint16_t PROGMEM COM_DOT_COMBO[] = {KC_COMMA, TD(TD_DOT), COMBO_END};
const uint16_t PROGMEM U_Y_COMBO[] = {LT_U_APP, KC_Y, COMBO_END};
const uint16_t PROGMEM H_COMMA_COMBO[] = {TD(TD_H_TODO), KC_COMM, COMBO_END};
const uint16_t PROGMEM S_COMMA_COMBO[] = {HOME_S, KC_COMMA, COMBO_END};
const uint16_t PROGMEM S_DOT_COMBO[] = {HOME_S, TD(TD_DOT), COMBO_END};
const uint16_t PROGMEM A_O_COMBO[] = {HOME_A, HOME_O, COMBO_END};
const uint16_t PROGMEM R_S_COMBO[] = {HOME_R, HOME_S, COMBO_END};
const uint16_t PROGMEM N_E_COMBO[] = {HOME_N, HOME_E, COMBO_END};
const uint16_t PROGMEM Q_QUOT_COMBO[] = {KC_Q, KC_QUOT, COMBO_END};
const uint16_t PROGMEM Z_SLASH_COMBO[] = {KC_Z, KC_SLASH, COMBO_END};
const uint16_t PROGMEM BSPC_E_V_COMBO[] = {LT_BSPC_NUMPAD, HOME_E, KC_V, COMBO_END};
const uint16_t PROGMEM BSPC_U_COMBO[] = {LT_BSPC_NUMPAD, LT_U_APP, COMBO_END};
const uint16_t PROGMEM BSPC_A_COMBO[] = {LT_BSPC_NUMPAD, HOME_A, COMBO_END};
const uint16_t PROGMEM BSPC_N_COMBO[] = {LT_BSPC_NUMPAD, HOME_N, COMBO_END};
const uint16_t PROGMEM BSPC_F_COMBO[] = {LT_BSPC_NUMPAD, LT_F_WINDOW, COMBO_END};
const uint16_t PROGMEM BSPC_H_COMBO[] = {LT_BSPC_NUMPAD, TD(TD_H_TODO), COMBO_END};
const uint16_t PROGMEM BSPC_T_COMBO[] = {LT_BSPC_NUMPAD, HOME_T, COMBO_END};
const uint16_t PROGMEM BSPC_M_COMBO[] = {LT_BSPC_NUMPAD, KC_M, COMBO_END};
const uint16_t PROGMEM BSPC_G_COMBO[] = {LT_BSPC_NUMPAD, KC_G, COMBO_END};
const uint16_t PROGMEM BSPC_O_COMBO[] = {LT_BSPC_NUMPAD, HOME_O, COMBO_END};
const uint16_t PROGMEM BSPC_I_COMBO[] = {LT_BSPC_NUMPAD, HOME_I, COMBO_END};
const uint16_t PROGMEM BSPC_I_S_COMBO[] = {LT_BSPC_NUMPAD, HOME_I, HOME_S, COMBO_END};
const uint16_t PROGMEM BSPC_T_A_COMBO[] = {LT_BSPC_NUMPAD, HOME_T, HOME_A, COMBO_END};
const uint16_t PROGMEM BSPC_Q_COMBO[] = {LT_BSPC_NUMPAD, KC_Q, COMBO_END};
const uint16_t PROGMEM BSPC_K_COMBO[] = {LT_BSPC_NUMPAD, KC_K, COMBO_END};
const uint16_t PROGMEM BSPC_T_S_COMBO[] = {LT_BSPC_NUMPAD, HOME_T, HOME_S, COMBO_END};
const uint16_t PROGMEM BSPC_T_H_COMBO[] = {LT_BSPC_NUMPAD, HOME_T, TD(TD_H_TODO), COMBO_END};
const uint16_t PROGMEM BSPC_D_N_COMBO[] = {LT_BSPC_NUMPAD, TD(TD_D_WOX), HOME_N, COMBO_END};
const uint16_t PROGMEM BSPC_L_COMBO[] = {LT_BSPC_NUMPAD, KC_L, COMBO_END};
const uint16_t PROGMEM BSPC_E_COMBO[] = {LT_BSPC_NUMPAD, HOME_E, COMBO_END};
const uint16_t PROGMEM BSPC_W_COMBO[] = {LT_BSPC_NUMPAD, KC_W, COMBO_END};
const uint16_t PROGMEM BSPC_P_COMBO[] = {LT_BSPC_NUMPAD, KC_P, COMBO_END};
const uint16_t PROGMEM BSPC_A_T_COMBO[] = {LT_BSPC_NUMPAD, HOME_A, HOME_T, COMBO_END};
const uint16_t PROGMEM BSPC_Z_COMBO[] = {LT_BSPC_NUMPAD, KC_Z, COMBO_END};
const uint16_t PROGMEM BSPC_I_T_COMBO[] = {LT_BSPC_NUMPAD, HOME_I, HOME_T, COMBO_END};
const uint16_t PROGMEM BSPC_O_T_COMBO[] = {LT_BSPC_NUMPAD, HOME_O, HOME_T, COMBO_END};
const uint16_t PROGMEM BSPC_B_COMBO[] = {LT_BSPC_NUMPAD, KC_B, COMBO_END};
const uint16_t PROGMEM J_U_COMBO[] = {KC_J, LT_U_APP, COMBO_END};
const uint16_t PROGMEM H_V_COMBO[] = {TD(TD_H_TODO), KC_V, COMBO_END};
const uint16_t PROGMEM Q_K_COMBO[] = {KC_Q, KC_K, COMBO_END};
const uint16_t PROGMEM K_B_COMBO[] = {KC_K, KC_B, COMBO_END};
const uint16_t PROGMEM W_A_COMBO[] = {KC_W, HOME_A, COMBO_END};
const uint16_t PROGMEM F_R_COMBO[] = {LT_F_WINDOW, HOME_R, COMBO_END};
const uint16_t PROGMEM F_A_COMBO[] = {LT_F_WINDOW, HOME_A, COMBO_END};
const uint16_t PROGMEM O_D_COMBO[] = {HOME_O, TD(TD_D_WOX), COMBO_END};
const uint16_t PROGMEM W_I_COMBO[] = {HOME_I, KC_W, COMBO_END};
const uint16_t PROGMEM I_E_COMBO[] = {HOME_I, HOME_E, COMBO_END};
const uint16_t PROGMEM A_K_COMBO[] = {HOME_A, KC_K, COMBO_END};
const uint16_t PROGMEM R_M_COMBO[] = {HOME_R, KC_M, COMBO_END};
const uint16_t PROGMEM S_Y_COMBO[] = {HOME_S, KC_Y, COMBO_END};
const uint16_t PROGMEM W_R_COMBO[] = {KC_W, HOME_R, COMBO_END};

// clang-format off
combo_t key_combos[] = {
	[WF_SCLN] = COMBO_ACTION(W_F_COMBO),
	[CK_EQUAL] = COMBO_ACTION(C_K_COMBO),
	[COMMA_DOT_BSLSH] = COMBO_ACTION(COM_DOT_COMBO),
	[UY_DASH] = COMBO_ACTION(U_Y_COMBO),
	[HCOMMA_BANG] = COMBO(H_COMMA_COMBO, KC_EXLM),
	[S_COMMA_LEFT_ARROW] = COMBO_ACTION(S_COMMA_COMBO),
	[S_DOT_RIGHT_ARROW] = COMBO_ACTION(S_DOT_COMBO),
	[AO_CAPSLOCK] = COMBO(A_O_COMBO, KC_CAPS),
	[RS_CAPSWORD] = COMBO(R_S_COMBO, KC_CAPS_WORD),
	[NE_ESC] = COMBO(N_E_COMBO, KC_ESC),
	[QQUOT_RESET] = COMBO(Q_QUOT_COMBO, QK_BOOT),
	[ZSLASH_POWER_OPTS] = COMBO_ACTION(Z_SLASH_COMBO),
	[BSPCEV_EVERY] = COMBO_ACTION(BSPC_E_V_COMBO),
	[BSPCU_YOU] = COMBO_ACTION(BSPC_U_COMBO),
	[BSPCU_AND] = COMBO_ACTION(BSPC_A_COMBO),
	[BSPCN_NOT] = COMBO_ACTION(BSPC_N_COMBO),
	[BSPCF_FOR] = COMBO_ACTION(BSPC_F_COMBO),
	[BSPCH_HERE] = COMBO_ACTION(BSPC_H_COMBO),
	[BSPCT_THE] = COMBO_ACTION(BSPC_T_COMBO),
	[BSPCM_MENT] = COMBO_ACTION(BSPC_M_COMBO),
	[BSPCG_ING] = COMBO_ACTION(BSPC_G_COMBO),
	[BSPCO_OUGH] = COMBO_ACTION(BSPC_O_COMBO),
	[BSPCI_ION] = COMBO_ACTION(BSPC_I_COMBO),
	[BSPCIS_IONS] = COMBO_ACTION(BSPC_I_S_COMBO),
	[BSPCTA_THAT] = COMBO_ACTION(BSPC_T_A_COMBO),
	[BSPCQ_QUE] = COMBO_ACTION(BSPC_Q_COMBO),
	[BSPCK_KEY] = COMBO_ACTION(BSPC_K_COMBO),
	[BSPCTS_THIS] = COMBO_ACTION(BSPC_T_S_COMBO),
	[BSPCTH_THAT] = COMBO_ACTION(BSPC_T_H_COMBO),
	[BSPCDN_DONT] = COMBO_ACTION(BSPC_D_N_COMBO),
	[BSPCL_LOOK] = COMBO_ACTION(BSPC_L_COMBO),
	[BSPCE_EYE] = COMBO_ACTION(BSPC_E_COMBO),
	[BSPCW_WHAT] = COMBO_ACTION(BSPC_W_COMBO),
	[BSPCP_PARA] = COMBO_ACTION(BSPC_P_COMBO),
	[BSPCAT_AND_THE] = COMBO_ACTION(BSPC_A_T_COMBO),
	[BSPC_Z_ZENGHAO] = COMBO_ACTION(BSPC_Z_COMBO),
	[BSPCAT_IN_THE] = COMBO_ACTION(BSPC_I_T_COMBO),
	[BSPCOT] = COMBO_ACTION(BSPC_O_T_COMBO),
	[BSPC_B_BASSOON] = COMBO_ACTION(BSPC_B_COMBO),
	[JU_JUST] = COMBO_ACTION(J_U_COMBO),
	[HV_HAVE] = COMBO_ACTION(H_V_COMBO),
	[QK_QMK] = COMBO_ACTION(Q_K_COMBO),
	[KB_KEYBOARD] = COMBO_ACTION(K_B_COMBO),
	[WA_WAS] = COMBO_ACTION(W_A_COMBO),
	[FR_FROM] = COMBO_ACTION(F_R_COMBO),
	[FA_FACE] = COMBO_ACTION(F_A_COMBO),
	[OD_OULD] = COMBO_ACTION(O_D_COMBO),
	[WI_WITH] = COMBO_ACTION(W_I_COMBO),
	[IE_IKE] = COMBO_ACTION(I_E_COMBO),
	[AK_AWKWARD] = COMBO_ACTION(A_K_COMBO),
	[RM_REMEMBER] = COMBO_ACTION(R_M_COMBO),
	[SY_SYMPHON] = COMBO_ACTION(S_Y_COMBO),
	[WR_WARD] = COMBO_ACTION(W_R_COMBO),
};
// clang-format on
void steno_combo(const char *lowercase, const char *uppercase, const char *ctrlcase, bool pressed, uint8_t mod_state, uint8_t oneshot_state) {
	if (pressed) {
		clear_mods();
		clear_oneshot_mods();
		if (uppercase && (mod_state | oneshot_state) & MOD_MASK_SHIFT) {
			unregister_mods(MOD_MASK_SHIFT);
			send_string(uppercase);
			set_mods(mod_state);
		} else if (ctrlcase && (mod_state | oneshot_state) & MOD_MASK_CTRL) {
			unregister_mods(MOD_MASK_CTRL);
			send_string(ctrlcase);
			set_mods(mod_state);
		} else {
			send_string(lowercase);
		}
		set_mods(mod_state);
	}
}

void process_combo_event(uint16_t combo_index, bool pressed) {
	uint8_t oneshot_state = get_oneshot_mods();
	action_tapping_process((keyrecord_t){});
	uint8_t mod_state = get_mods();
	switch(combo_index) {
		case WF_SCLN:
			steno_combo(";", ":", SS_LCTL(":"), pressed, mod_state, oneshot_state);
			break;
		case CK_EQUAL:
			steno_combo("=", "+", SS_LCTL("="), pressed, mod_state, oneshot_state);
			break;
		case COMMA_DOT_BSLSH:
			steno_combo("\\", "|", SS_LCTL("\\"), pressed, mod_state, oneshot_state);
			break;
		case UY_DASH:
			steno_combo("-", "_", SS_LCTL("-"), pressed, mod_state, oneshot_state);
			break;
		case S_COMMA_LEFT_ARROW:
			steno_combo("<-", NULL, "<=", pressed, mod_state, oneshot_state);
			break;
		case S_DOT_RIGHT_ARROW:
			steno_combo("->", NULL, "=>", pressed, mod_state, oneshot_state);
			break;
		case ZSLASH_POWER_OPTS:
			steno_combo(SS_LGUI(SS_TAP(X_X)) SS_DELAY(200) SS_TAP(X_U), NULL, NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCEV_EVERY:
			steno_combo("every", "Every", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCU_YOU:
			steno_combo("you", "You", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCU_AND:
			steno_combo("and", "And", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCN_NOT:
			steno_combo("not", "Not", "n't", pressed, mod_state, oneshot_state);
			break;
		case BSPCF_FOR:
			steno_combo("for", "For", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCH_HERE:
			steno_combo("here", "Here", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCT_THE:
			steno_combo("the", "The", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCM_MENT:
			steno_combo("ment", "Ment", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCG_ING:
			steno_combo("ing", "Ing", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCO_OUGH:
			steno_combo("ough", "Ough", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCI_ION:
			steno_combo("ion", "Ion", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCIS_IONS:
			steno_combo("ions", "Ions", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCTA_THAT:
			steno_combo("that", "That", "that's", pressed, mod_state, oneshot_state);
			break;
		case BSPCQ_QUE:
			steno_combo("que", "Que", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCK_KEY:
			steno_combo("key", "Key", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCTS_THIS:
			steno_combo("this", "This", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCTH_THAT:
			steno_combo("that", "That", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCDN_DONT:
			steno_combo("don't", "Don't", "do not", pressed, mod_state, oneshot_state);
			break;
		case BSPCL_LOOK:
			steno_combo("look", "Look", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCE_EYE:
			steno_combo("eye", "Eye", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCW_WHAT:
			steno_combo("what", "What", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCP_PARA:
			steno_combo("para", "Para", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCAT_AND_THE:
			steno_combo("and the", "And the", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPC_Z_ZENGHAO:
			steno_combo("zenghao", "Zenghao", "Zenghao Wang", pressed, mod_state, oneshot_state);
			break;
		case BSPCAT_IN_THE:
			steno_combo("in the", "In the", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPCOT:
			steno_combo("on the", "On the", NULL, pressed, mod_state, oneshot_state);
			break;
		case BSPC_B_BASSOON:
			steno_combo("bassoon", "Bassoon", NULL, pressed, mod_state, oneshot_state);
			break;
		case JU_JUST:
			steno_combo("just", "Just", NULL, pressed, mod_state, oneshot_state);
			break;
		case HV_HAVE:
			steno_combo("have", "Have", NULL, pressed, mod_state, oneshot_state);
			break;
		case QK_QMK:
			steno_combo("qmk", "QMK", NULL, pressed, mod_state, oneshot_state);
			break;
		case KB_KEYBOARD:
			steno_combo("keyboard", "Keyboard", NULL, pressed, mod_state, oneshot_state);
			break;
		case WA_WAS:
			steno_combo("was", "Was", NULL, pressed, mod_state, oneshot_state);
			break;
		case FR_FROM:
			steno_combo("from", "From", NULL, pressed, mod_state, oneshot_state);
			break;
		case FA_FACE:
			steno_combo("face", "Face", NULL, pressed, mod_state, oneshot_state);
			break;
		case OD_OULD:
			steno_combo("ould", "Ould", NULL, pressed, mod_state, oneshot_state);
			break;
		case WI_WITH:
			steno_combo("with", "With", NULL, pressed, mod_state, oneshot_state);
			break;
		case IE_IKE:
			steno_combo("ike", "Ike", NULL, pressed, mod_state, oneshot_state);
			break;
		case AK_AWKWARD:
			steno_combo("awkward", "Awkward", NULL, pressed, mod_state, oneshot_state);
			break;
		case RM_REMEMBER:
			steno_combo("remember", "Remember", NULL, pressed, mod_state, oneshot_state);
			break;
		case SY_SYMPHON:
			steno_combo("symphon", "Symphon", NULL, pressed, mod_state, oneshot_state);
			break;
		case WR_WARD:
			steno_combo("ward", "Ward", NULL, pressed, mod_state, oneshot_state);
			break;
	}
};
